services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCS_BASE_URL=${DOCS_BASE_URL:-null}
        - SELF_HOSTED_SHARE=${SELF_HOSTED_SHARE:-true}
    image: livecodes/latest
    restart: unless-stopped
    environment:
      - HOST_NAME=${HOST_NAME:-localhost}
      - PORT=${PORT:-8080}
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379

  valkey:
    image: valkey/valkey:8.1.2-alpine3.22
    restart: unless-stopped
    volumes:
      - ./server/data/valkey:/data
    command: ['valkey-server', '--save', '60', '1', '--loglevel', 'warning']

  server:
    image: caddy:2.10.0-alpine
    entrypoint: ['/bin/sh', './entrypoint.sh']
    command: ['caddy', 'run', '--config', '/etc/caddy/Caddyfile', '--adapter', 'caddyfile']
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '${PORT:-8080}:${PORT:-8080}'
    environment:
      - HOST_NAME=${HOST_NAME:-localhost}
      - PORT=${PORT:-8080}
    volumes:
      - ./server/entrypoint.sh:/srv/entrypoint.sh
      - ./server/Caddyfile:/etc/caddy/Caddyfile
      - ./server/data/caddy/data:/data
      - ./server/data/caddy/config:/config
    depends_on:
      - app
