services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCS_BASE_URL=${DOCS_BASE_URL:-null}
    image: livecodes/latest
    restart: unless-stopped
    environment:
      - HOST_NAME=${HOST_NAME:-localhost}
      - PORT=${PORT:-8080}
      - DOCS_BASE_URL=${DOCS_BASE_URL:-null}

  server:
    image: caddy:2-alpine
    entrypoint: ['/bin/sh', './entrypoint.sh']
    command: ['caddy', 'run', '--config', '/etc/caddy/Caddyfile', '--adapter', 'caddyfile']
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '${PORT:-8080}:${PORT:-8080}'
    environment:
      - HOST_NAME=${HOST_NAME:-localhost}
      - PORT=${PORT:-8080}
    volumes:
      - ./server/entrypoint.sh:/srv/entrypoint.sh
      - ./server/Caddyfile:/etc/caddy/Caddyfile
      - ./server/.caddy/data:/data
      - ./server/.caddy/config:/config
    depends_on:
      - app
