services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SELF_HOSTED=true
        - SELF_HOSTED_SHARE=${SELF_HOSTED_SHARE:-true}
        - SELF_HOSTED_BROADCAST=${SELF_HOSTED_BROADCAST:-true}
        - BROADCAST_PORT=${BROADCAST_PORT:-3030}
        - SANDBOX_HOST_NAME=${SANDBOX_HOST_NAME:-${HOST_NAME:-livecodes.localhost}}
        - SANDBOX_PORT=${SANDBOX_PORT:-8090}
        - FIREBASE_CONFIG=${FIREBASE_CONFIG:-}
        - DOCS_BASE_URL=${DOCS_BASE_URL:-null}
    restart: unless-stopped
    environment:
      - SELF_HOSTED=true
      - HOST_NAME=${HOST_NAME:-livecodes.localhost}
      - PORT=${PORT:-443}
      - SELF_HOSTED_SHARE=${SELF_HOSTED_SHARE:-true}
      - SELF_HOSTED_BROADCAST=${SELF_HOSTED_BROADCAST:-true}
      - BROADCAST_PORT=${BROADCAST_PORT:-3030}
      - BROADCAST_TOKENS=${BROADCAST_TOKENS:-}
      - SANDBOX_HOST_NAME=${SANDBOX_HOST_NAME:-${HOST_NAME:-livecodes.localhost}}
      - SANDBOX_PORT=${SANDBOX_PORT:-8090}
      - LOG_URL=${LOG_URL:-null}
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
    volumes:
      - ./assets:/srv/build/assets

  valkey:
    image: valkey/valkey:8.1.2-alpine3.22
    restart: on-failure
    volumes:
      - ./data/valkey:/data
    command:
      [
        'sh',
        '-c',
        'if [ "$SELF_HOSTED_SHARE" != "false" ]; then valkey-server --save 60 1 --loglevel warning; fi',
      ]

  server:
    image: caddy:2.10.0-alpine
    entrypoint: ['/bin/sh', './entrypoint.sh']
    command: ['caddy', 'run', '--config', '/etc/caddy/Caddyfile', '--adapter', 'caddyfile']
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '${PORT:-443}:${PORT:-443}'
      - '${SANDBOX_PORT:-8090}:${SANDBOX_PORT:-8090}'
      - '${BROADCAST_PORT:-3030}:${BROADCAST_PORT:-3030}'
    environment:
      - HOST_NAME=${HOST_NAME:-livecodes.localhost}
      - PORT=${PORT:-443}
      - SANDBOX_HOST_NAME=${SANDBOX_HOST_NAME:-${HOST_NAME:-livecodes.localhost}}
      - SANDBOX_PORT=${SANDBOX_PORT:-8090}
      - BROADCAST_PORT=${BROADCAST_PORT:-3030}
    volumes:
      - ./server/entrypoint.sh:/srv/entrypoint.sh
      - ./server/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
    depends_on:
      - app
